### ISSUE TITLE
Internet connection

### ISSUE THREAD

**Issue by aghozlane** [kellylab/viral-protein-function-plm#1] opened 2024-01-30 10:01 UTC
Dear developpers,

Thank you for this work. I am impressed by the very low amount of code required. 
Our gpu nodes are not connected to internet. Is possible to download the required data once with a specific set of options ?

**Comment by zachflam** [comment] 2024-01-30 15:42
Thank you! 
The issue with the internet is related to a single download of the protein language model (https://huggingface.co/Rostlab/prot_bert_bfd) in the Biotransformers package (https://github.com/DeepChainBio/bio-transformers). The model is cached locally (.cache/huggingface/transformers) after initial download and the path is checked in all subsequent calls to BioTransformers(backend='protbert_bfd', num_gpus=num_gpus) in the protbert_bfd_embed_utils.py script of this project. 

Though there is no way to explicitly do this with our code at this time, if you download the protein language model using Biotransformers locally and upload it to the node to the path '~/.cache/huggingface/transformers' along with the rest of the code base it might circumvent the internet download. 

If this does not work, there appears to be a TRANSFORMERS_OFFLINE mode in the transformers package that we could use to build an offline mode for the model.

**Comment by yikiii** [comment] 2024-01-31 02:20
Thank you for this work.
I have connection problem too
`"Connection error, and we cannot find the requested files in the cached path."
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.`

So I
`cd .cache/huggingface/transformers`

`aria2c https://storage.googleapis.com/alphafold-databases/casp14_versions/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz`

is it right?

**Comment by zachflam** [comment] 2024-01-31 03:10
@yikiii what you are attempting to download there is not the Rostlab/prot_bert_bfd huggingface model as far as I can tell. Here is the protein language model needed- https://huggingface.co/Rostlab/prot_bert_bfd

What you need to do is download the model in a python script using the transformers library so that it is cached to the path `~/.cache/huggingface/transformers`. This must be done in the conda environment constructed from plm_vpf_embed.yml to ensure that the transformers version is correct. 

Here is a python script to download the model:
```
from transformers import BertForMaskedLM, BertTokenizer
BertTokenizer.from_pretrained('Rostlab/prot_bert_bfd', do_lower_case=False, padding=True)
BertForMaskedLM.from_pretrained('Rostlab/prot_bert_bfd').to("cuda")
```

Once you run this script, the protbert_bfd_embed_utils.py script of this repo should initialize the BioTransformers class without needing to access the internet.

**Comment by yikiii** [comment] 2024-01-31 04:50
Thanks for your reply!
It works!

**Comment by aghozlane** [comment] 2024-01-31 16:21
In my case the small python script can't work. The master node doesn't have any gpu.

I get a runtime error:
```
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by lonelycrab888** [comment] 2024-01-31 18:10
This issue comes from the bio-transformers package and can be correctly executed by the following method.
Locate the position of the biotransformers package in the conda environment, and modify the file at ...../biotransformers/utils/constant.py:
’ROSTLAB_LIST = ["Rostlab/prot_bert", "Rostlab/prot_bert_bfd", "your download path"]
MAPPING_PROTBERT = {"protbert": "Rostlab/prot_bert","protbert_bfd": "your download path",}’

**Comment by lonelycrab888** [comment] 2024-01-31 18:11
This issue comes from the bio-transformers package and can be correctly executed by the following method.
Locate the position of the biotransformers package in the conda environment, and modify the file at ...../biotransformers/utils/constant.py:
#ROSTLAB_LIST = ["Rostlab/prot_bert", "Rostlab/prot_bert_bfd", "your download path"]
##MAPPING_PROTBERT = {"protbert": "Rostlab/prot_bert","protbert_bfd": "your download path",}

**Comment by lonelycrab888** [comment] 2024-01-31 18:17
This issue comes from the bio-transformers package and can be correctly executed by the following method.
Locate the position of the biotransformers package in the conda environment, and modify the file at ...../biotransformers/utils/constant.py:
```python
ROSTLAB_LIST = ["Rostlab/prot_bert",  "Rostlab/prot_bert_bfd",  "your download path"]
MAPPING_PROTBERT = {"protbert" : "Rostlab/prot_bert",  "protbert_bfd" : "your download path"）
```

**Comment by lonelycrab888** [comment] 2024-01-31 18:22
> Thank you! The issue with the internet is related to a single download of the protein language model (https://huggingface.co/Rostlab/prot_bert_bfd) in the Biotransformers package (https://github.com/DeepChainBio/bio-transformers). The model is cached locally (.cache/huggingface/transformers) after initial download and the path is checked in all subsequent calls to BioTransformers(backend='protbert_bfd', num_gpus=num_gpus) in the protbert_bfd_embed_utils.py script of this project.
> 
> Though there is no way to explicitly do this with our code at this time, if you download the protein language model using Biotransformers locally and upload it to the node to the path '~/.cache/huggingface/transformers' along with the rest of the code base it might circumvent the internet download.
> 
> If this does not work, there appears to be a TRANSFORMERS_OFFLINE mode in the transformers package that we could use to build an offline mode for the model but that would require some development.

This issue comes from the bio-transformers package and we can make some minor modifications to the biotransformers package to implement an offline mode.
Locate the position of the biotransformers package in the conda environment, and modify the file at ...../biotransformers/utils/constant.py:

```python
ROSTLAB_LIST = ["Rostlab/prot_bert", "Rostlab/prot_bert_bfd", "your download path"]
MAPPING_PROTBERT = {"protbert": "Rostlab/prot_bert","protbert_bfd": "your download path"）
```

**Comment by zachflam** [comment] 2024-02-01 15:11
Thanks @lonelycrab888 for the suggestion. In this case, how did you download the huggingface model? This might help @aghozlane with their issue.

**Comment by yikiii** [comment] 2024-02-02 07:17
I'm sorry, actually I encountered the same error as well...
```
from transformers import BertForMaskedLM, BertTokenizer
BertTokenizer.from_pretrained('Rostlab/prot_bert_bfd', do_lower_case=False, padding=True)
```
is ok, but when
`BertForMaskedLM.from_pretrained('Rostlab/prot_bert_bfd').to("cuda")`

`RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`


I also encountered errors previously when trying to run some software due to the lack of an NVIDIA GPU, such as Guppy GPU-accelerated, so I believe this is caused by the absence of an NVIDIA GPU rather than the failure to download the model.

And I got the results through the Google Colab notebook.

**Comment by lonelycrab888** [comment] 2024-02-02 09:19
> Thanks @lonelycrab888 for the suggestion. In this case, how did you download the huggingface model? This might help @aghozlane with their issue.

Open this link 
```python
 https://huggingface.co/Rostlab/prot_bert_bfd/tree/main
``` and download all the files contained there (simply click on the download button), then store the downloaded files in a folder. Use the path of this new folder to replace the 'your download path' that I mentioned above.

**Comment by lonelycrab888** [comment] 2024-02-02 09:24
> I'm sorry, actually I encountered the same error as well...
> 
> ```
> from transformers import BertForMaskedLM, BertTokenizer
> BertTokenizer.from_pretrained('Rostlab/prot_bert_bfd', do_lower_case=False, padding=True)
> ```
> 
> is ok, but when `BertForMaskedLM.from_pretrained('Rostlab/prot_bert_bfd').to("cuda")`
> 
> `RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx`
> 
> I also encountered errors previously when trying to run some software due to the lack of an NVIDIA GPU, such as Guppy GPU-accelerated, so I believe this is caused by the absence of an NVIDIA GPU rather than the failure to download the model.
> 
> And I got the results through the Google Colab notebook.

In fact, the error you're experiencing is not the same; as you've mentioned, it's a GPU error, whereas the one above pertains to a network error and offline mode issue.

For your error, you might try removing the
```python
 .to("cuda")
``` 
  to load the model onto the CPU.

```python
from transformers import BertForMaskedLM, BertTokenizer
BertTokenizer.from_pretrained('Rostlab/prot_bert_bfd', do_lower_case=False, padding=True)
BertForMaskedLM.from_pretrained('Rostlab/prot_bert_bfd')
```

**Comment by zachflam** [comment] 2024-02-02 14:13
Agreed with @lonelycrab888 that the issue is downloading and loading the model onto a CPU in which case you would not use the `.to("cuda")` on download. Our code can handle this situation if you run the bash script `faa_prediction.sh` with default --num_gpus parameter (which default = 0 and results in Biotransformers downloading the PLM in cpu mode).

**Comment by zachflam** [comment] 2024-02-02 14:13
> > Thanks @lonelycrab888 for the suggestion. In this case, how did you download the huggingface model? This might help @aghozlane with their issue.
> 
> Open this link
> 
> ```python
>  https://huggingface.co/Rostlab/prot_bert_bfd/tree/main
> ```
> 
> and download all the files contained there (simply click on the download button), then store the downloaded files in a folder. Use the path of this new folder to replace the 'your download path' that I mentioned above.

@aghozlane did this approach work?

**Comment by aghozlane** [comment] 2024-02-08 12:14
Yes it solved the situation. I also had to update pytorch in the conda, because of this error:
`NVIDIA A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70`

It runs now, I cross fingers

**Closed** 2024-02-09 04:31 UTC
Labels: bug
